export const projects = [
  {
    title: "Motion Study",
    image: "/img1.jpeg",
    year: 2024,
    // href: "/sample-project",
  },
  {
    title: "Idle Form",
    image: "/img2.jpeg",
    year: 2023,
    // href: "/sample-project",
  },
  {
    title: "Blur Signal",
    image: "/img3.jpeg",
    year: 2024,
    // href: "/sample-project",
  },
  {
    title: "Still Drift",
    image: "/img4.jpeg",
    year: 2023,
    // href: "/sample-project",
  },
  {
    title: "Tidewalk",
    image: "/img5.jpeg",
    year: 2024,
    // href: "/sample-project",
  },
  {
    title: "Core Motion",
    image: "/img6.jpeg",
    year: 2022,
    // href: "/sample-project",
  },
  {
    title: "White Bloom",
    image: "/img7.jpeg",
    year: 2024,
    // href: "/sample-project",
  },
  {
    title: "Backrun",
    image: "/public/img8.jpeg",
    year: 2023,
    // href: "/sample-project",
  },
  {
    title: "Rushline",
    image: "/img9.jpeg",
    year: 2024,
    // href: "/sample-project",
  },
  {
    title: "Afterimage",
    image: "/img10.jpeg",
    year: 2023,
    // href: "/sample-project",
  },
  {
    title: "Shadowhead",
    image: "/img11.jpeg",
    year: 2022,
    // href: "/sample-project",
  },
  {
    title: "Opal Lace",
    image: "/public/img12.jpeg",
    year: 2024,
    // href: "/sample-project",
  },
  {
    title: "Glassprint",
    image: "/img13.jpeg",
    year: 2024,
    // href: "/sample-project",
  },
  {
    title: "Redshift",
    image: "/img14.jpeg",
    year: 2023,
    // href: "/sample-project",
  },
  {
    title: "White Noise",
    image: "/public/img15.jpeg",
    year: 2023,
    // href: "/sample-project",
  },
  {
    title: "Twin Field",
    image: "/public/img16.jpeg",
    year: 2024,
    // href: "/sample-project",
  },
  {
    title: "Petalloop",
    image: "/public/img17.jpeg",
    year: 2023,
    // href: "/sample-project",
  },
  {
    title: "Ghostwalk",
    image: "/public/img18.jpeg",
    year: 2024,
    // href: "/sample-project",
  },
  {
    title: "Heatwave",
    image: "/public/img19.jpeg",
    year: 2023,
    // href: "/sample-project",
  },
  {
    title: "Sky Drift",
    image: "/public/img20.jpeg",
    year: 2024,
    // href: "/sample-project",
  },
  {
    title: "Spindle",
    image: "/public/img21.jpeg",
    year: 2022,
    // href: "/sample-project",
  },
  {
    title: "Pacer",
    image: "/public/img22.jpeg",
    year: 2023,
    // href: "/sample-project",
  },
  {
    title: "Stride",
    image: "/public/img23.jpeg",
    year: 2024,
    // href: "/sample-project",
  },
  {
    title: "Cryo Pulse",
    image: "/public/img24.jpeg",
    year: 2022,
    // href: "/sample-project",
  },
  {
    title: "Velvet Blur",
    image: "/public/img25.jpeg",
    year: 2024,
    // href: "/sample-project",
  },
];
